services:
  mong_db:
    container_name: smartdelta-mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo_db:/data/db

  api:
    build: ./smartdelta-backend-ts
    ports:
      - "5001:5001"
    volumes:
      - ./smartdelta-backend-ts:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"]
    environment:
      PORT: 5001
      DATA_SCIENCE_API_URL: http://data-science-api:5006
      FRONTEND_URL: http://frontend:3000
      MONGO_DB_CONNECTION_STRING: mongodb://mong_db:27017/
      NODE_ENV: "development"
      MONGO_DB_DATABASE_NAME: "SmartDeltaApi"
      MULTER_CSV_DIR: "src/data/uploads/csvData"
      OPENAI_API_KEY: "" # get your api key from openai
      ENCRYPTION_KEY: "" # put 256-bit AES key here, you can generate with `openssl rand -base64 32` command. It has to be same with REACT_APP_SECRET_KEY
    depends_on:
      - mong_db

  frontend:
    build: ./smartdelta-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./smartdelta-frontend:/usr/src/app:delegated
      - /usr/src/app/node_modules/
    depends_on:
      - api
      - mong_db
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SECRET_KEY=  # put 256-bit AES key here, you can generate with `openssl rand -base64 32` command. It has to be same with ENCRYPTION_KEY

  data-science-api:
    build: ./smartdelta-ml-backend
    ports:
      - "5006:5006"
    depends_on:
      - api
    environment:
      FLASK_ENV: "development"
      FLASK_APP: "app.py"
volumes:
  mongo_db: {}
